### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AkshayPatil1994** [ipadjen/geowrapper#1]
Just wanted to leave this as a request
- Progress monitor to screen 

Thanks Ivan!

**Comment by ipadjen** [comment]
The core of the alpha wrap is a flood filling algorithm with refinement. So you cannot know a priori the size of the refinement to create the typical 0-100 progress bar.
However, I might just output the queue (numbers will go up due to refinement and eventually down to 0) so that a user is aware something is happening?

**Comment by ipadjen** [comment]
Added in 365b03b. Will release it soon.
